apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app-cd
  template:
    metadata:
      labels:
        app: reddit-app-cd
    spec:
      containers:
        - name: reddit-app-cd
          image: nehakyatham/reddit-clone-pipe:1.0.0-1
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
