apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  labels:
    app: reddit-app-cd 
spec:
  selector:
    app: reddit-app-cd

  ports:
    - port: 80
      targetPort: 3000

  type: LoadBalancer
